# Generated by Django 5.1 on 2024-12-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='contraseña',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
